CREATE TABLE IF NOT EXISTS {{table}} (
    unique_row_id          text,
    filename               text,
    VendorID               text,
    lpep_pickup_datetime   timestamp,
    lpep_dropoff_datetime  timestamp,
    store_and_fwd_flag     text,
    RatecodeID             text,
    PULocationID           text,
    DOLocationID           text,
    passenger_count        integer,
    trip_distance          double precision,
    fare_amount            double precision,
    extra                  double precision,
    mta_tax                double precision,
    tip_amount             double precision,
    tolls_amount           double precision,
    ehail_fee              double precision,
    improvement_surcharge  double precision,
    total_amount           double precision,
    payment_type           integer,
    trip_type              integer,
    congestion_surcharge   double precision
);
